language: scala
scala: 2.11.12

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2

sudo: required

services:
  - docker

before_script:
  - docker network create test-gitbase-spark-connector
  - docker run -d --rm --name bblfshd --privileged -p 9432:9432 bblfsh/bblfshd:v2.9.1-drivers
  - docker network connect test-gitbase-spark-connector bblfshd

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:MaxMetaspaceSize=1024M clean scalastyle coverage test coverageReport assembly

after_success:

- bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: deploy
      if: tag IS present OR (branch = master AND env(TRAVIS_PULL_REQUEST) IS present)
      jdk: openjdk8

      install: skip
      before_script: skip

      script:
        - openssl aes-256-cbc -K $encrypted_0c5015980dfd_key -iv $encrypted_0c5015980dfd_iv -in key.asc.enc -out key.asc -d
        - gpg --no-default-keyring --primary-keyring ./project/.gnupg/pubring.gpg --secret-keyring ./project/.gnupg/secring.gpg --keyring ./project/.gnupg/pubring.gpg --fingerprint --import key.asc
        - make build
        - cp target/gitbase-spark-connector-uber.jar "gitbase-spark-connector-$TRAVIS_TAG.jar"
#        - make docker-push

      deploy:
        - provider: script
          script: make maven-release
          skip_cleanup: true
          on:
            tags: true
        - provider: releases
          api_key:
            secure: $GITHUB_TOKEN
          file_glob: true
          file: "*.jar"
          skip_cleanup: true
          on:
            tags: true
